import { Vocabulary, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'common', name: 'Giao tiếp cơ bản', icon: 'MessageCircle', description: 'Các câu chào hỏi và hội thoại thông dụng.' },
  { id: 'family', name: 'Gia đình', icon: 'Users', description: 'Từ vựng về các thành viên trong gia đình.' },
  { id: 'food', name: 'Ẩm thực', icon: 'Utensils', description: 'Tên các món ăn và hoạt động ăn uống.' },
  { id: 'travel', name: 'Du lịch', icon: 'Plane', description: 'Từ vựng khi đi du lịch và hỏi đường.' },
  { id: 'work', name: 'Công việc', icon: 'Briefcase', description: 'Môi trường văn phòng và nghề nghiệp.' },
  { id: 'numbers', name: 'Số đếm', icon: 'Hash', description: 'Các con số từ cơ bản đến nâng cao.' },
];

export const INITIAL_VOCABULARY: Vocabulary[] = [
  {
    id: '1',
    word: '你好',
    pinyin: 'nǐ hǎo',
    meaning: 'Xin chào',
    example: '你好！很高兴见到你。',
    examplePinyin: 'Nǐ hǎo! Hěn gāoxìng jiàndào nǐ.',
    exampleMeaning: 'Xin chào! Rất vui được gặp bạn.',
    category: 'common',
  },
  {
    id: '2',
    word: '谢谢',
    pinyin: 'xièxie',
    meaning: 'Cảm ơn',
    example: '谢谢你的帮助。',
    examplePinyin: 'Xièxie nǐ de bāngzhù.',
    exampleMeaning: 'Cảm ơn sự giúp đỡ của bạn.',
    category: 'common',
  },
  {
    id: '3',
    word: '爸爸',
    pinyin: 'bàba',
    meaning: 'Bố',
    example: '我爸爸是一名老师。',
    examplePinyin: 'Wǒ bàba shì yī míng lǎoshī.',
    exampleMeaning: 'Bố tôi là một giáo viên.',
    category: 'family',
  },
  {
    id: '4',
    word: '妈妈',
    pinyin: 'māma',
    meaning: 'Mẹ',
    example: '我妈妈很爱我。',
    examplePinyin: 'Wǒ māma hěn ài wǒ.',
    exampleMeaning: 'Mẹ tôi rất yêu tôi.',
    category: 'family',
  },
  {
    id: '5',
    word: '米饭',
    pinyin: 'mǐfàn',
    meaning: 'Cơm',
    example: '我想吃一碗米饭。',
    examplePinyin: 'Wǒ xiǎng chī yī wǎn mǐfàn.',
    exampleMeaning: 'Tôi muốn ăn một bát cơm.',
    category: 'food',
  },
  {
    id: '6',
    word: '北京',
    pinyin: 'Běijīng',
    meaning: 'Bắc Kinh',
    example: '我想去北京旅游。',
    examplePinyin: 'Wǒ xiǎng qù Běijīng lǚyóu.',
    exampleMeaning: 'Tôi muốn đi du lịch Bắc Kinh.',
    category: 'travel',
  },
  {
    id: '7',
    word: '工作',
    pinyin: 'gōngzuò',
    meaning: 'Làm việc / Công việc',
    example: '你在这儿工作多久了？',
    examplePinyin: 'Nǐ zài zhèr gōngzuò duōjiǔ le?',
    exampleMeaning: 'Bạn làm việc ở đây bao lâu rồi?',
    category: 'work',
  },
  {
    id: '8',
    word: '一',
    pinyin: 'yī',
    meaning: 'Số một',
    example: '这一共是一块钱。',
    examplePinyin: 'Zhè yígòng shì yíkuài qián.',
    exampleMeaning: 'Cái này tổng cộng là một đồng.',
    category: 'numbers',
  },
  {
    id: '9',
    word: '二',
    pinyin: 'èr',
    meaning: 'Số hai',
    example: '我有两个朋友。',
    examplePinyin: 'Wǒ yǒu liǎng gè péngyǒu.',
    exampleMeaning: 'Tôi có hai người bạn.',
    category: 'numbers',
  },
  {
    id: '10',
    word: '三',
    pinyin: 'sān',
    meaning: 'Số ba',
    example: '三月是春天的开始。',
    examplePinyin: 'Sānyuè shì chūntiān de kāishǐ.',
    exampleMeaning: 'Tháng ba là sự bắt đầu của mùa xuân.',
    category: 'numbers',
  },
  {
    id: '11',
    word: '十',
    pinyin: 'shí',
    meaning: 'Số mười',
    example: '我们在这儿住了十年了。',
    examplePinyin: 'Wǒmen zài zhèr zhùle shí nián le.',
    exampleMeaning: 'Chúng tôi đã sống ở đây mười năm rồi.',
    category: 'numbers',
  },
  {
    id: '12',
    word: '百',
    pinyin: 'bǎi',
    meaning: 'Trăm',
    example: '这个书包一百块。',
    examplePinyin: 'Zhège shūbāo yìbǎi kuài.',
    exampleMeaning: 'Cái cặp sách này giá một trăm đồng.',
    category: 'numbers',
  },
];
